"""refactor_stock_ledger_and_rbac

Revision ID: f0c62d52b53e
Revises: 3241953910ba
Create Date: 2026-09-26 15:47:43.629394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c62d52b53e'
down_revision: Union[str, Sequence[str], None] = '3241953910ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('otp', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_resets_email'), 'password_resets', ['email'], unique=False)
    op.create_index(op.f('ix_password_resets_id'), 'password_resets', ['id'], unique=False)
    op.create_table('stock_quants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name='_product_location_uc')
    )
    op.create_index(op.f('ix_stock_quants_id'), 'stock_quants', ['id'], unique=False)
    op.add_column('products', sa.Column('per_unit_cost', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('min_stock_level', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('reorder_quantity', sa.Float(), nullable=True))
    op.add_column('stock_movements', sa.Column('reference', sa.String(), nullable=True))
    op.add_column('stock_movements', sa.Column('responsible_id', sa.Integer(), nullable=True))
    op.add_column('stock_movements', sa.Column('partner_name', sa.String(), nullable=True))
    op.add_column('stock_movements', sa.Column('contact_email', sa.String(), nullable=True))
    op.add_column('stock_movements', sa.Column('reference_code', sa.String(), nullable=True))
    op.add_column('stock_movements', sa.Column('schedule_date', sa.DateTime(), nullable=True))
    op.add_column('stock_movements', sa.Column('contact', sa.String(), nullable=True))
    op.create_index(op.f('ix_stock_movements_reference'), 'stock_movements', ['reference'], unique=True)
    op.create_foreign_key('fk_stock_movements_responsible_id_users', 'stock_movements', 'users', ['responsible_id'], ['id'])
    op.add_column('users', sa.Column('role', sa.Enum('INVENTORY_MANAGER', 'WAREHOUSE_STAFF', name='userrole'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_constraint('fk_stock_movements_responsible_id_users', 'stock_movements', type_='foreignkey')
    op.drop_index(op.f('ix_stock_movements_reference'), table_name='stock_movements')
    op.drop_column('stock_movements', 'contact')
    op.drop_column('stock_movements', 'schedule_date')
    op.drop_column('stock_movements', 'reference_code')
    op.drop_column('stock_movements', 'contact_email')
    op.drop_column('stock_movements', 'partner_name')
    op.drop_column('stock_movements', 'responsible_id')
    op.drop_column('stock_movements', 'reference')
    op.drop_column('products', 'reorder_quantity')
    op.drop_column('products', 'min_stock_level')
    op.drop_column('products', 'per_unit_cost')
    op.drop_index(op.f('ix_stock_quants_id'), table_name='stock_quants')
    op.drop_table('stock_quants')
    op.drop_index(op.f('ix_password_resets_id'), table_name='password_resets')
    op.drop_index(op.f('ix_password_resets_email'), table_name='password_resets')
    op.drop_table('password_resets')
    # ### end Alembic commands ###
